### ISSUE TITLE
Difference to num-bigint?

### ISSUE THREAD

**Issue by FliegendeWurst** [Starfunk/largeint#1]
That crate does about the same thing. What makes this crate better?

**Comment by Starfunk** [comment]
You are correct in saying that both crates are extremely similar. I developed the largeint crate because I wanted a quick and dirty way of using arbitrarily large integers in Rust. I'm working on making largeint's documentation clearer and more intuitive so anyone can quickly and easily install and use largeint without having to spend a lot of time looking over the small details. Although I haven't run any benchmarks, I am fairly confident num-bigint is much more efficient than largeint, therefore largeint is really just for those looking to run tests with large integers (or play around with large integers) and not for those planning on implementing large integers permanently into their programs. For example, largeint is a simple and easy-to-use way of solving [Project Euler problem 13](https://projecteuler.net/problem=13), which requires the use of integers larger than u128.  

Thank you for the question,  I should make it more clear that this is my intention for this crate.
